# Generated by Django 5.1.15 on 2026-04-21 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(help_text='Full project description. Supports plain text or Markdown.')),
                ('github_link', models.URLField(help_text='Link to the GitHub repository.', max_length=500)),
                ('live_demo', models.URLField(blank=True, default='', help_text='Optional link to a live demo.', max_length=500)),
                ('image', models.ImageField(help_text='Project cover image (JPG, PNG, GIF, WebP, or SVG).', upload_to='projects/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])])),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project at the top of the listing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, help_text='Technologies used in this project.', related_name='projects', to='projects.technology')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
